### ISSUE TITLE
Disappearing allocations

### ISSUE THREAD

**Issue by boyanpenkov** [pythonspeed/filprofiler#149] opened 2021-04-05 17:00 UTC
Hello folks,

When running, I get lots of goodies like:

```
=fil-profile= WARNING: Somehow an allocation of size 22048 disappeared. This can happen if e.g. a library frees memory with private OS APIs. If this happens only a few times with small allocations, it doesn't really matter. If you see this happening a lot, or with large allocations, please file a bug.

```

Most of the calls we're making are in numpy and torch.

What information would you folks like?

Do write, and cheers!

**Comment by itamarst** [comment] 2021-04-05 20:03
Hi,

Thanks for reporting a bug. What operating system is this, what version of Fil, what version of Python, and what libraries are using? Just NumPy/PyTorch, or additional ones as well?

**Comment by boyanpenkov** [comment] 2021-04-05 22:01
Hello folks -- 

This is on Debian testing.  

```
filprofiler               2021.04.0        py39h2551b06_0    conda-forge
```
As for other libs -- matplotlib, namedtuple from collections, logging, sys, pathlib, io, pickle, gc -- nothing too exotic....

Cheers!

**Comment by itamarst** [comment] 2021-04-05 23:23
PyTorch seems like the most likely candidate so I will glance it; I wonder if it's using one of the more obscure memory allocation APIs that Fil doesn't support yet.

**Comment by boyanpenkov** [comment] 2021-04-05 23:58
Super -- please let me know if you need any input from my end...

**Comment by itamarst** [comment] 2021-04-07 18:21
One bug I discovered is that if you install `pytorch` using pip but use the Conda version of `filprofiler` certain allocations won't get tracked, due to an unfortunate concatenation of circumstances. So that's one possibility; if you're installing `pytorch` via pip, that's plausibly what's going on.

If not—

1. Are you using GPUs?
2. Are you using subprocesses? In particular with fork() without exec().
3. Any chance you could provide a minimal reproducer?

**Comment by boyanpenkov** [comment] 2021-04-07 18:29
> One bug I discovered is that if you install `pytorch` using pip but use the Conda version of `filprofiler` certain allocations won't get tracked, due to an unfortunate concatenation of circumstances. So that's one possibility; if you're installing `pytorch` via pip, that's plausibly what's going on.

I can confirm both are installed with conda.

> 
> If not—
> 
>     1. Are you using GPUs?

No.

> 
>     2. Are you using subprocesses? In particular with fork() without exec().

I do use ``from multiprocessing import Process``

> 
>     3. Any chance you could provide a minimal reproducer?

Uh, I'll have to see in a bit here, as the code I'm on is private for a bit here, but can look again (on a new example..) in a few days.

**Comment by itamarst** [comment] 2021-04-07 19:12
OK, opened #152 for the pip vs. Conda issue.

`multiprocessing.Process` could be it I suppose. In theory Fil will shutdown in subprocesses, since it doesn't support them, but perhaps it isn't. So will look at that while waiting for reproducer if you can manage one (thank you!).

**Comment by itamarst** [comment] 2021-04-08 02:06
More questions:

1. Are you using `fil-profile run`, the API, or Jupyter magic?
2. If you're using the API, are you starting profiling in the parent process, the child process, or both?

**Comment by boyanpenkov** [comment] 2021-04-08 10:28
``fil-profile run``, haven't tried the other options.

**Comment by itamarst** [comment] 2021-04-10 15:17
Can't figure out how this is happening. So, next steps:

1. I will change default output so it tells you what % of allocations were affected. Decent chance that this bug doesn't actually impact the results in a meaningful way, so at least you know you can rely on the profiling results.
2. Will add optional debugging code to figure out tracebacks of disappeared allocations.

**Comment by itamarst** [comment] 2021-04-13 11:54
Attached you will find a ZIP file. Unzip, and install the wheel matching your version of Python. It has the two improvements mentioned above.

1. The default output should be much more useful, and should hopefully let you know whether current results are distorted by missing allocations or not. Hopefully you can just start using Fil in its current state.
2. If you do `export FIL_DEBUG=1`, you will get tracebacks for each missing allocation, so you can tell what code allocated it. If you could include some of those tracebacks, and if it's not obvious tell me which APIs are being used and context they're being run in (process, thread), that would be very helpful. With any luck that'll give some sense why the allocations are disappearing.

**Comment by boyanpenkov** [comment] 2021-04-14 16:36
Can confirm that all of my errors are torch matrix multiplications, so this might be more of a torch thing -- or the way fil-profiler interacts with pytorch.

**Comment by itamarst** [comment] 2021-04-14 16:38
Thanks, that should help with reproducer, though if you can give me a self-contained code snippet to reproduce that would be even better.

**Comment by itamarst** [comment] 2021-04-14 17:39
Release `2021.04.2` with the improved warning messages should be available later today (PyPI) or tomorrow (Conda).

**Comment by itamarst** [comment] 2021-04-14 17:48
I am unable to reproduce missing allocations with a simplistic Torch matrix multiplication:

```python
import torch

tensor1 = torch.randn(3000, 3000)
tensor2 = torch.randn(3000, 3000)
tensor1 * tensor2
tensor1.matmul(tensor2)
```

As such, a reproducer would be very helpful.

**Comment by boyanpenkov** [comment] 2021-04-14 20:01
A correction; they are actually gpytorch allocations, which should use pytorch, but may be doing some thing more subtle.

The traceback is:
```
=fil-profile= The allocation from this traceback disappeared:
=| examples/postprocess_example.py:339 (<module>)
=| examples/postprocess_example.py:74 (get_a_model)
=| /home/boyan/Vazhno/Work/Repos/precog/precog/gp/training.py:154 (recursive_training)
=| /home/boyan/Vazhno/Work/Repos/precog/precog/gp/training.py:237 (exact_training)
=| /home/boyan/miniconda3/envs/precog/lib/python3.9/site-packages/gpytorch/module.py:28 (__call__)
=| /home/boyan/miniconda3/envs/precog/lib/python3.9/site-packages/gpytorch/mlls/exact_marginal_log_likelihood.py:62 (forward)
=| /home/boyan/miniconda3/envs/precog/lib/python3.9/site-packages/gpytorch/distributions/multivariate_normal.py:169 (log_prob)
=| /home/boyan/miniconda3/envs/precog/lib/python3.9/site-packages/gpytorch/lazy/lazy_tensor.py:1069 (inv_quad_logdet)
=| /home/boyan/miniconda3/envs/precog/lib/python3.9/site-packages/gpytorch/functions/_inv_quad_log_det.py:122 (forward)
=| /home/boyan/miniconda3/envs/precog/lib/python3.9/site-packages/gpytorch/lazy/psd_sum_lazy_tensor.py:12 (zero_mean_mvn_samples)
=| /home/boyan/miniconda3/envs/precog/lib/python3.9/site-packages/gpytorch/lazy/psd_sum_lazy_tensor.py:12 (<genexpr>)
=| /home/boyan/miniconda3/envs/precog/lib/python3.9/site-packages/gpytorch/lazy/lazy_tensor.py:1725 (zero_mean_mvn_samples)
=| /home/boyan/miniconda3/envs/precog/lib/python3.9/site-packages/gpytorch/lazy/lazy_tensor.py:1125 (matmul)
=| /home/boyan/miniconda3/envs/precog/lib/python3.9/site-packages/gpytorch/functions/_matmul.py:21 (forward)
=| /home/boyan/miniconda3/envs/precog/lib/python3.9/site-packages/gpytorch/lazy/non_lazy_tensor.py:44 (_matmul)
```

and this stems from 
```
    likelihood = gpytorch.likelihoods.GaussianLikelihood().to(device)
    optimizer = torch.optim.Adam(
        model.parameters(), lr=lr
    )
    mll = gpytorch.mlls.ExactMarginalLogLikelihood(likelihood, model)
    signal = torch.randn(10000, 1)
    for i in range(10):
        # Zero gradients from previous iteration
        optimizer.zero_grad()
        # Output from model
        output = model(time)
        # Calc loss and backprop gradients
        loss = -mll(output, signal)
```

"device" in this case is CPU-only, as there's no GPU on this machine.

**Comment by itamarst** [comment] 2021-04-15 20:52
Hm. That seems to fall back to `torch.matmul`, though.

**Comment by boyanpenkov** [comment] 2021-04-15 20:58
Agreed, and I don't have good intuition about how the lazy allocations are handed, if any...

**Comment by itamarst** [comment] 2021-04-15 21:01
So I discovered while poking around a really severe bug in Fil, and I can't figure out a way it would result in what you're seeing, but maybe? So going to release 2021.04.3 with fix. Should be available on Conda-Forge by tomorrow, if you could retry with that and see if it helps?

**Comment by boyanpenkov** [comment] 2021-04-15 21:03
Super -- I'll check tomorrow, and see what's up -- will report to this thread...

**Comment by itamarst** [comment] 2021-04-15 21:03
Thank you!

**Comment by itamarst** [comment] 2021-04-16 22:13
I have a theory, which I have applied in the following wheels. If you could try this and let me know if it fixes the problem?

[ubuntu-20.04-3.8-wheel.zip](https://github.com/pythonspeed/filprofiler/files/6328077/ubuntu-20.04-3.8-wheel.zip)

Thank you!

**Comment by boyanpenkov** [comment] 2021-04-16 23:26
I ran today on 2021.04.3 -- from conda-forge -- and observe no issues with it calling missed allocations.

Runtime is long, so still waiting for the fil report.

**Comment by itamarst** [comment] 2021-04-16 23:35
Newer versions of the code only print a warning right at the end, during report generation time, not during runtime. So that may or may not be informative.

**Comment by boyanpenkov** [comment] 2021-04-16 23:37
Ahh, ok, then I'll have to wait till this finishes running, and will then report back...

**Comment by boyanpenkov** [comment] 2021-04-17 19:34
Confirming I see
```
=fil-profile= WARNING: 121.92% (17407923380 bytes) of tracked memory somehow disappeared. If this is a small percentage you can just ignore this warning, since the missing allocations won't impact the profiling results. If the % is high, please run `export FIL_DEBUG=1` to get more output', re-run Fil on your script, and then file a bug report at https://github.com/pythonspeed/filprofiler/issues/new

```

Now running with DEBUG=1

**Comment by boyanpenkov** [comment] 2021-04-17 19:34
Yep, it's the same stuff with the matmuls that gpytorch calls, with DEBUG on.

**Comment by boyanpenkov** [comment] 2021-04-17 19:37
> I have a theory, which I have applied in the following wheels. If you could try this and let me know if it fixes the problem?
> 
> [ubuntu-20.04-3.8-wheel.zip](https://github.com/pythonspeed/filprofiler/files/6328077/ubuntu-20.04-3.8-wheel.zip)
> 
> Thank you!

Confirming I am now running with this, with DEBUG, and see the lost allocations messages.

**Comment by itamarst** [comment] 2021-04-17 19:58
Sigh. Really need to figure this out, that's a lot of memory... I really appreciate your testing this!

Any chance you can give a fully working reproducer? I can't run the above since it doesn't  have info to create a `model` object.

**Comment by itamarst** [comment] 2021-04-17 20:01
Meanwhile going to try some of the gpytorch example notebooks.

**Comment by itamarst** [comment] 2021-04-17 21:46
Could you also include the output of `conda list`? Thanks.

**Comment by itamarst** [comment] 2021-04-17 22:23
Or rather, `conda env export`.

**Comment by boyanpenkov** [comment] 2021-04-19 21:56
[bip_conda_env.txt](https://github.com/pythonspeed/filprofiler/files/6339323/bip_conda_env.txt)

Please find attached the conda env from the relevant machine.

**Comment by itamarst** [comment] 2021-04-20 22:57
Thanks, I had been installing from conda-forge so this'll help make my tests match yours better.

**Comment by itamarst** [comment] 2021-04-23 21:07
Thanks for the code! What is the difference between the two ZIP files?

**Comment by itamarst** [comment] 2021-04-23 21:07
And, what command specifically did you run to trigger the warnings?

**Comment by boyanpenkov** [comment] 2021-04-23 21:13
One does not trigger the fil issues, and is clear of known memory leaks, and the other does.  So, if fil is known not to track leaked memory, then we're OK.

```
make synthetic_data
python examples/postprocess_example.py
```

**Comment by itamarst** [comment] 2021-04-23 21:42
Is this expected?

```
2021-04-23 17:41:39,149 INFO next is the slidingwindows one
/home2/itamarst2/miniconda3/envs/gpytorch/lib/python3.9/site-packages/gpytorch/distributions/multivariate_normal.py:259: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
Traceback (most recent call last):
  File "/home/itamarst/Devel/memory-profiler/precog2/examples/postprocess_example.py", line 403, in <module>
    fig, ax = run_slidingwindowevents_on_path(
  File "/home/itamarst/Devel/memory-profiler/precog2/examples/postprocess_example.py", line 295, in run_slidingwindowevents_on_path
    sliding_windows = sliding_window(time, signal, called_events)
  File "/home/itamarst/Devel/memory-profiler/precog2/precog/analysis/postprocess.py", line 55, in sliding_window
    finish = time[i + 1 + w]
IndexError: index 10000 is out of bounds for dimension 0 with size 10000
```

**Comment by boyanpenkov** [comment] 2021-04-23 22:58
On one branch, yeah -- does it mess up your testing?

**Comment by itamarst** [comment] 2021-04-23 23:01
I did get a few missing allocations on that code, but it was a tiny amount, so I'm curious if keeping running would give more. Will try the other branch too.

**Comment by itamarst** [comment] 2021-04-26 12:05
I have a theory: race condition.

Thread 1: malloc() -> address A.
Thread 1: Store metadata for address A.

Later, thread 1 and thread 2 interleave:

Thread 1: free(A)
Thread 2: malloc() -> address A.
Thread 2: Store metadata for address A. But there is already metadata for A, so it gets overwritten.
Thread 1: Delete metadata for address A. Wrong metadata gets deleted—the version from thread 2.

I am guessing your computer is faster and has more cores, making this occur more often.

The solution is, I think, to swap the order of operations in `free()` and `realloc()`: first do the metadata removal and only then actually free the memory.

**Comment by boyanpenkov** [comment] 2021-04-26 12:21
I'm not surprised -- our changes this last week basically consisted of forcing Python's gc and torch's empty_cache() to do things explicitly in a bunch of places, so that may well be it, but between our four machines, it was coming up intermittently...

If this was misleading, sorry about that!

**Comment by itamarst** [comment] 2021-04-26 13:08
So, did some testing, and while I still think the above is a real bug, fixing it doesn't fix the problem :cry:

**Comment by boyanpenkov** [comment] 2021-04-26 13:13
In fil or in ours?

**Comment by itamarst** [comment] 2021-04-26 13:18
I fixed the bug in Fil, but still seeing warnings from Fil about disappearing allocations when running your code.

**Comment by itamarst** [comment] 2021-04-26 13:19
(Unless you're writing C code, and it's buggy, code you write should never cause Fil to get confused.)

**Comment by boyanpenkov** [comment] 2021-04-26 13:23
Aha, OK -- no problem.  What version did the bugfix get into in fil?  Do you see massive amounts of disappearing allocations, or occasional small ones?

I think the best way to move forward is  for us to keep running fil on our stuff as it evolves, and to keep reporting...

We are not writing C (directly, at least...) here...

Glad *something* got fixed!

**Comment by itamarst** [comment] 2021-04-27 21:20
Yeah I should release that fix. Also it occurred me that potentially the FIL_DEBUG path could actually compound the disappearing allocations problem, because (A) it runs some Python code which could trigger GC and (B) it's in reentrant mode, so anything GC cleans up would disappear! So need to make sure I prevent that.

**Comment by itamarst** [comment] 2021-04-28 23:02
New release (2021.04.4) should be available soon. It adds even more debug info (on free()s of unknown addresses), though that hasn't helped me catch anything, plus the fix for race condition. Let me know if it helps.

**Comment by itamarst** [comment] 2021-04-30 12:20
2021.04.4 is available now, when you have a chance would love to hear if it's any better.

**Comment by boyanpenkov** [comment] 2021-05-03 15:06
I after ``export FIL_DEBUG`` I get multiple hits of:
```
=fil-profile= The allocation from this traceback disappeared:
=| examples/generic_example.py:99 (<module>)
=| examples/generic_example.py:62 (run_example_on_path)
=| /home/boyan/Vazhno/Work/Repos/precog/precog/gp/training.py:172 (iterative_training)
=| /home/boyan/Vazhno/Work/Repos/precog/precog/gp/training.py:255 (exact_training)
=| /home/boyan/miniconda3/envs/precog/lib/python3.9/site-packages/gpytorch/module.py:28 (__call__)
=| /home/boyan/miniconda3/envs/precog/lib/python3.9/site-packages/gpytorch/mlls/exact_marginal_log_likelihood.py:62 (forward)
=| /home/boyan/miniconda3/envs/precog/lib/python3.9/site-packages/gpytorch/distributions/multivariate_normal.py:169 (log_prob)
=| /home/boyan/miniconda3/envs/precog/lib/python3.9/site-packages/gpytorch/lazy/lazy_tensor.py:1069 (inv_quad_logdet)
=| /home/boyan/miniconda3/envs/precog/lib/python3.9/site-packages/gpytorch/functions/_inv_quad_log_det.py:67 (forward)
=| /home/boyan/miniconda3/envs/precog/lib/python3.9/site-packages/gpytorch/lazy/added_diag_lazy_tensor.py:100 (_preconditioner)
=| /home/boyan/miniconda3/envs/precog/lib/python3.9/site-packages/gpytorch/utils/pivoted_cholesky.py:68 (pivoted_cholesky)
=| /home/boyan/miniconda3/envs/precog/lib/python3.9/site-packages/gpytorch/utils/memoize.py:59 (g)
=| /home/boyan/miniconda3/envs/precog/lib/python3.9/site-packages/gpytorch/lazy/lazy_tensor.py:910 (evaluate)
=| /home/boyan/miniconda3/envs/precog/lib/python3.9/site-packages/gpytorch/lazy/interpolated_lazy_tensor.py:408 (matmul)
=| /home/boyan/miniconda3/envs/precog/lib/python3.9/site-packages/gpytorch/utils/interpolation.py:189 (left_interp)
```

So I think your recent patches narrow this down nicely to problems in gpytorch!

**Comment by itamarst** [comment] 2021-05-03 15:09
I don't think it's actually gpytorch's fault, I think it's still FIl :(. Are you seeing fewer, at least?

**Comment by boyanpenkov** [comment] 2021-05-03 15:12
Certainly fewer, but if an outside lib leaks memory (like, straight-up does not clean up after ``malloc()``), how does Fil handle that?

**Comment by itamarst** [comment] 2021-05-03 15:17
Leaks are fine, from Fil's perspective. Bugs that involve outright memory corruption would confuse Fil, but I haven't seen any of those.

**Comment by itamarst** [comment] 2021-05-06 23:20
Can you try the latest version, 2021.05.0, and see if this fixes it? Thank you!

**Comment by boyanpenkov** [comment] 2021-05-14 18:44
Well, sorry about the delay there -- running now...

For reference, my ``conda list`` shows he 2021.5.0, but 
```
(precog) → real_data Repos/precog fil-profile --version                           14:43:02
0.0.0
```
Not sure if that version string is what you meant.

**Comment by itamarst** [comment] 2021-05-14 18:51
Thanks! Probably a bug, I'll open an issue.

**Comment by boyanpenkov** [comment] 2021-05-14 22:30
Allrighty, confirming I see no leak errors on 2021.05 on the workload I had -- I'll set some things to run this weekend and continue to look, but good news!

**Comment by itamarst** [comment] 2021-05-18 12:25
Thank you for all your help, Fil is much better now in many ways beyond this particular bug. I'm going to close this now, and if it reoccurs please open a new bug.

I would also love to hear if Fil is actually _useful_ for your particular problems :)

**Closed by itamarst** 2021-05-18 12:25 UTC
Labels: NEXT, bug

**Comment by boyanpenkov** [comment] 2021-05-18 19:57
@itamarst  -- super, glad to hear it, and yes, fil is now the first profiler I reach for!

Thanks kindly for your efforts, and cheers!
