### ISSUE TITLE
Windows support in the future

### ISSUE THREAD

**Issue by DanielDM325** [pythonspeed/filprofiler#388] opened 2022-07-10 20:50 UTC
According to the requirements only Linux and macOS are currently supported. Are there any plans to include Windows in the future?

**Comment by itamarst** [comment] 2022-07-12 01:36
In theory it's a thing I'd like to do someday. See #53 (original issue for this) for notes so far.

**Comment by itamarst** [comment] 2022-07-22 13:10
Closing this as duplicate of #53, follow that ticket if you're interested.

**Closed** 2022-07-22 13:10 UTC
