### ISSUE TITLE
feature request - support decorator

### ISSUE THREAD

**Issue by ChaimBlau** [pythonspeed/filprofiler#111] opened 2021-01-08 16:28 UTC
## Version information
Fil: 0.13.1
Python: 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0]

The option to decorate the function that you really want to profile is very helpful, for example when you have some data preparation _before_ you send your actual function to the cloud, but for some reason it hard to isolate the function to separate the function to script. This feature supported in memory_profiler, and it would be great to have it here too.

Thanks!

**Comment by itamarst** [comment] 2021-01-08 18:22
Thanks for the feature request. Are you doing this as part of manual profiling?

**Comment by itamarst** [comment] 2021-02-11 19:40
Going to say this is duplicate of #71, work will happen there.

**Closed by itamarst** 2021-02-11 19:40 UTC
Labels: NEXT
