### ISSUE TITLE
Many missing allocations on MacOS

### ISSUE THREAD

**Issue by Rosswell** [pythonspeed/filprofiler#160] opened 2021-04-14 01:31 UTC
hello! getting lots of 
```
=fil-profile= WARNING: Somehow an allocation of size 24 disappeared. This can happen if e.g. a library frees memory with private OS APIs. If this happens only a few times with small allocations, it doesn't really matter. If you see this happening a lot, or with large allocations, please file a bug.
```
warnings of various sizes (though the vast majority seem to be < 100) when using pandas to wrap SQL results in a dataframe. Unsure if its relevant or not, but this is reading query results from a snowflake DB.

context:
```
python v3.7.9
macOS catalina v10.15.7
pandas==1.1.5
filprofiler==2021.4.0
```

example snippet:
```python
from filprofiler.api import profile
import pandas as pd 

connection = get_snowflake_connection()  # returns SQLAlchemy connectable object 
sql = 'select * from test_table;'
result = profile(lambda: pd.read_sql(sql, con=connection), '/Users/rblanchard/fil-result')
```

and then I run the profiler via 
```
fil-profile python mem_prof.py
```

**Comment by itamarst** [comment] 2021-04-14 12:09
Hi, sorry you're seeing this problem. This may (or may not) be the same issue as #149, but at least you can use the debugging improvements I've been working on.

[macos-latest-3.7-wheel.zip](https://github.com/pythonspeed/filprofiler/files/6310671/macos-latest-3.7-wheel.zip)

Above you will find a ZIP file. Unzip, and install the wheel. It has two improvements:

* The default output should be much more useful, and should hopefully let you know whether current results are distorted by missing allocations or not. Hopefully you can just start using Fil in its current state.
* If you do export FIL_DEBUG=1, you will get tracebacks for each missing allocation, so you can tell what code allocated it. If you could include some of those tracebacks, and if it's not obvious tell me which APIs are being used and context they're being run in (process, thread), that would be very helpful. With any luck that'll give some sense why the allocations are disappearing.

**Comment by itamarst** [comment] 2021-04-14 12:10
As far as read_sql goes, have you seen my article on reducing memory usage? https://pythonspeed.com/articles/pandas-sql-chunking/

**Comment by itamarst** [comment] 2021-04-14 15:01
Thank you!

OK, so first, it looks you can ignore the missing allocations and keep using Fil given it's only worst case 0.3%, so that's good.

Second, I will go and merge the branch that includes the improved Fil warning+debugging messages.

Third, I will try to figure out what's going with these allocations... might be something about thread locals which is not something I can solve, but will see.

**Comment by Rosswell** [comment] 2021-04-14 15:05
sounds great, thanks for the help! ill start using that version in my testing. if you're interested, this is what i have so far in this performance investigation, fwiw 
![image](https://user-images.githubusercontent.com/24869120/114733417-27e3e000-9cf8-11eb-85c4-02435eb94ee3.png)

**Comment by itamarst** [comment] 2021-04-14 15:16
Nice, that is very thorough!

**Comment by itamarst** [comment] 2021-04-14 15:18
Leaving open since I still want to investigate what's causing the allocation to disappear (systemic issue in Fil or unsolvable edge case).

**Comment by Rosswell** [comment] 2021-04-14 15:24
> Leaving open since I still want to investigate what's causing the allocation to disappear (systemic issue in Fil or unsolvable edge case).

Ah shoot, sorry about that

**Comment by itamarst** [comment] 2021-04-14 17:39
Release `2021.04.2` with the improved warning messages should be available later today (PyPI) or tomorrow (Conda).

**Comment by Rosswell** [comment] 2021-04-14 17:44
for future reference, since im going to continue to use this tool for my profiling, at what % missing allocations would you start being concerned? I realize this is pretty dependent upon context, if we think about it in terms of % error, then different use cases would have different thresholds for error % that they're ok with accepting. But I am more wondering if there's some level where you personally would question the viability of the results entirely?

**Comment by itamarst** [comment] 2021-04-14 18:09
I actually drop smaller allocations if there's lots of them, so you're not always seeing 100% of allocations (I try to keep it to 99%, but if there are tens of thounsands of tiny allocations some of those will get dropped too).

This particular error is ... overcounting memory usage, really. There are allocations that were apparently freed but Fil didn't notice, and is only noticing now that the address is being reused. So (a) the failure mode is you focus optimization on wrong place and (b) the number is _known_ missing allocations, there might be others.

So it depends in part on allocation patterns (lots of big ones, lots of small ones), but general optimization guidelines tend to be "focus on largest parts of the data". Better to focus on code that is using 40% than code that is using 1% of memory/time/CPU.

Thus, if there's clear spot to optimize that's 40% of memory, you don't care if even 10% is being counted erroneously. If you're down to optimizing 2% of memory usage at a time, missing 10% is bad because maybe you're optimizing allocations that are actually non-existent...

**Comment by itamarst** [comment] 2021-04-16 21:32
Hi, could you upgrade to the latest release (2021.04.3) and see if it fixes this? It probably doesn't, but it has a pretty major bugfix so can't hurt to try.

**Comment by itamarst** [comment] 2021-04-16 22:40
If my theory is correct, the problem would only occur in sufficiently complex programs (w/lots of functions). So might be able to create my own reproducer that way (but that won't be happening today).

**Comment by itamarst** [comment] 2021-05-06 23:20
Can you try the latest version, 2021.05.0, and see if this fixes it? Has a bunch of relevant bug fixes (and also important bug fixes in general). Thank you!

**Comment by itamarst** [comment] 2021-05-18 12:26
Based on a number of bugfixes related to this and #149, I'm going to say this is probably fixed now. If it reoccurs, please file a new issue. Thank you for reporting this, feedback is always very valuable.

**Closed by itamarst** 2021-05-18 12:26 UTC
Labels: NEXT, bug
